### PR TITLE
fix: prevent cascading overrides clobbering typography

### PR DESCRIPTION
**Pull request by joshuawootonn**

### CODE REVIEW

**Comment by joshuawootonn** [comment]
https://github.com/makeswift/makeswift/assets/20950876/fe99fc05-bd7b-4fa0-a0ca-f54014545d6c

**Comment by joshuawootonn** [comment]
@apledger mentioned I should just make this match what we are doing in the sidebar, which led me to finding this part of the rich text panel. 

CleanShot 2023-06-13 at 15 37 51@2x

**Comment by migueloller** [comment]
@joshuawootonn, nice work. I've got a question. How does this impact overrides when there's no typography being used? Will tablet and mobile till properly inherit from larger devices?

**Review by migueloller — APPROVED** [review]

**Comment by joshuawootonn** [comment]
https://github.com/makeswift/makeswift/assets/20950876/f45e0fcd-6d9f-491c-bb6f-48482c8a9350

https://github.com/makeswift/makeswift/assets/20950876/ce48ef09-c5eb-4f38-be0c-ba0a9c8be6d2


https://github.com/makeswift/makeswift/assets/20950876/3b538d1a-064b-4611-8f02-8701f4c75571




https://github.com/makeswift/makeswift/assets/20950876/8117d54a-ec83-4a0c-b40e-a38356ffae43


https://github.com/makeswift/makeswift/assets/20950876/9827e26a-4435-4c39-81a3-7dec34cfa2e9



https://github.com/makeswift/makeswift/assets/20950876/f1c11dd6-643a-410b-a3b2-b74fc9b6439d

**Comment by joshuawootonn** [comment]
Kinda a long explanation to answer your question @migueloller ^

**Pull request merged**
