### PR TITLE
fix: fix bug in translation of detached typography

### PR DESCRIPTION
**Pull request by joshuawootonn**
Prior to translation we normalize all our `typography` richtext data to the highest ancestor for the simplest possible markup. To do this we go through children determining what parts of `typography` they share. Any `typography` data that is shared is pushed up the tree, while unique `typography` data is left behind.

We do an `and` and an `xor` to determine what is shared and unique. In the case of detached `typography` the logic was incorrect. It was pushing data up the tree wtihout removing it from the original location. This left our normalization in a infinite loop.

My hunch is I added this special case as an optimization, so I am just removing it.

### CODE REVIEW

**Comment by joshuawootonn** [comment]
This is the branch I'll be shipping this with: `0.14-stable`

This was the branch naming pattern I had previously created patches with.

**Comment by migueloller** [comment]
> This is the branch I'll be shipping this with: `0.14-stable`
> 
> This was the branch naming pattern I had previously created patches with.

Sorry, I'm a bit confused here. Does the branch have some sort of important meaning? When doing the release there should be a git tag from changesets that points to the commit so the original branch for the PR can be deleted and we'll still have a reference to the commit that the release as for.

**Comment by joshuawootonn** [comment]
> > This is the branch I'll be shipping this with: `0.14-stable`
> > This was the branch naming pattern I had previously created patches with.
> 
> Sorry, I'm a bit confused here. Does the branch have some sort of important meaning? When doing the release there should be a git tag from changesets that points to the commit so the original branch for the PR can be deleted and we'll still have a reference to the commit that the release as for.

True. I think I had the idea from other conversations that we needed to maintain a branch for manually patched versions, but you are right.

**Comment by joshuawootonn** [comment]
Going to cut a release for this change

**Comment by joshuawootonn** [comment]
Not sure how this test is failing.

**Pull request merged**
