### PR TITLE
fix: revert builtin components width control to use styled components

### PR DESCRIPTION
**Pull request by fikrikarim**

### CODE REVIEW

**Review by migueloller — APPROVED** [review]
Looks good 👍🏻

**Comment by fikrikarim** [comment]
I tested every built-in component's width locally, and they look great.

**Comment by migueloller** [comment]
> I tested every built-in component's width locally, and they look great.

There were some components—I think Navigation was one of them—that re-used some of the builtin components like Button and Image. When I moved these to a class I accidentally shipped some bugs because it was very hard to see where those props were being passed (some of them were just spread). Did you check for that too @fikrikarim?

**Comment by fikrikarim** [comment]
> > I tested every built-in component's width locally, and they look great.
> 
> There were some components—I think Navigation was one of them—that re-used some of the builtin components like Button and Image. When I moved these to a class I accidentally shipped some bugs because it was very hard to see where those props were being passed (some of them were just spread). Did you check for that too @fikrikarim?
> 
> It's possible that for those my solution was moving it back to Styled Components so this might not be an issue

Ah you're right. I missed those. I updated the `Image` and `Button`. There should be no more components that use `responsiveWidth` directly.

**Review by migueloller — APPROVED** [review]

**Pull request merged**
